name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    environment: production
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: openweather_app
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');" 
    - name: Set up environment variables
      run: |
          echo "ALGOLIA_APP_ID=".${{ secrets.ALGOLIA_APP_ID }}
          echo "ALGOLIA_SECRET=".${{ secrets.ALGOLIA_SECRET_KEY }}
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/openweather_app.sql
    - name: Compile Dev Assets
      run: |
        npm ci --no-audit
        npm run build    
    - name: Execute tests using Pest PHP
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: openweather_app
        ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
        ALGOLIA_SECRET: ${{ secrets.ALGOLIA_SECRET_KEY }}
      run: |
        php artisan migrate
        php artisan db:seed --class=CitySeeder
        php artisan test
      
